[Feature] 공유하기 기능으로 ticlemoa 앱을 켜고, ShareNavigationController 실행하기
depromeet/nyongnyong_iOS pull request #107
Opened 2023-01-02 07:59 UTC by sustainable-git

## 📌 배경

close #106

## 내용
- Project.swift에서 ShareExtension에 해당하는 info.plist 수정
- 사용하지 않는 Targets/ShareExtension/Resources 폴더 제거

## 테스트 방법 (optional)
![image](https://user-images.githubusercontent.com/81242125/210205223-53f021bf-9420-4f33-8e64-38bb9e5057d1.jpeg)

실행 타겟을 ShareExtension으로 변경하고 Safari를 실행한 후, 아무 사이트에서 공유하기를 눌러 ticlemoa를 선택

2023-01-02 09:09 UTC, joseph704 requested changes
해당 브랜치(feature/Share)에서 tuist clean -> tuist fetch -> tuist generate 시 에러가 나네요.
확인 부탁드립니다!
<img width="762" alt="image" src="https://user-images.githubusercontent.com/35060252/210211910-6d238588-d5f2-4bf7-83dc-ad2ab1c82c7a.png">

2023-01-02 21:48 UTC, kipsong133 approved these changes

2023-01-02 22:26 UTC, keeplo commented
이 에러는 ShareExtension 디렉토리에 Resources 라는 이름으로 디렉토리 하나 생성해보시고 다시 시도해봐주시겠어요?
디렉토리 구성됬어도 안에 파일이 없으면 깃헙에 안올라와서 가끔 발생하네요 ㅠㅠ
다른데는 `Localizable.strings` 같은 파일로 임시로 해놨는데 놓친 부분인것 같습니다

2023-01-02 22:26 UTC, keeplo approved these changes
고생하셨습니다

2023-01-03 00:49 UTC, sustainable-git commented
@joseph704 

일단 저는 에러가 안나는데 확인해보겠습니다.

![image](https://user-images.githubusercontent.com/81242125/210287838-3a02b02e-de83-4b22-83cc-ae436c5e9aee.jpeg)

2023-01-03 01:18 UTC, joseph704 commented
@sustainable-git 
@kipsong133 
@keeplo 

Resources라는 폴더 생성하고 안에 Localizable.strings 파일 넣은다음 tuist generate 하니깐 해당 에러는 사라졌습니다. 
![image](https://user-images.githubusercontent.com/35060252/210288990-ee840f36-03b6-47eb-9654-ea44a2afc9dd.png)

**대신, 다음과 같이 컴파일이 안되네요.. Xcode/DerivedData 폴더 날려도 봤는데 안되네요. 제 환경 왜이러죠ㅋㅋㅋㅋ** 
![image](https://user-images.githubusercontent.com/35060252/210289048-38444e19-7cae-4256-a301-d34507e07eef.png)

혹시 다른 분들 컴파일 되신다면 일단 머지하고 develop에서 다시 컴파일 해볼까요? ㅎㅎ

2023-01-03 01:36 UTC, sustainable-git commented
@joseph704 

저거 bridge header 문제일텐데... 저게 왜 발생할까요...

2023-01-03 04:28 UTC, joseph704 approved these changes
@keeplo @kipsong133 @sustainable-git 
일단은 다른 분들 잘빌드 되시는 것 같으니, approve하고 머지된 후 develop 브랜치에서 확인해 보겠습니다! 
고생하셨습니다!

2023-01-03 04:37 UTC, keeplo commented
> @sustainable-git @kipsong133 @keeplo
> 
> Resources라는 폴더 생성하고 안에 Localizable.strings 파일 넣은다음 tuist generate 하니깐 해당 에러는 사라졌습니다. ![image](https://user-images.githubusercontent.com/35060252/210288990-ee840f36-03b6-47eb-9654-ea44a2afc9dd.png)
> 
> **대신, 다음과 같이 컴파일이 안되네요.. Xcode/DerivedData 폴더 날려도 봤는데 안되네요. 제 환경 왜이러죠ㅋㅋㅋㅋ** ![image](https://user-images.githubusercontent.com/35060252/210289048-38444e19-7cae-4256-a301-d34507e07eef.png)
> 
> 혹시 다른 분들 컴파일 되신다면 일단 머지하고 develop에서 다시 컴파일 해볼까요? ㅎㅎ

이 PR 버전은 현재 develop과 다른버전이라서 의존성이 살짝 미적용되어있습니다 ㅠㅠ
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/24707229/210300638-842fbe9a-5bcc-4375-acc7-fc13f7e2b63e.png">
처럼 `Project.swift`  파일을 수정해주시면 빌드가 될거에요! 
제가 놓친 부분입니다 죄송해요 ㅠㅠ

UserInterface 모듈을 import 해서 사용하려면 ShareExtension 모듈에 의존되어야 하는데
모듈간 연결이 되지않아서 위와 같은 에러를 발생했습니다.

제가 언급한 수정 부분은 두 모듈의 의존관계를 형성하는 부분입니다.

2023-01-03 04:44 UTC, joseph704 commented
@keeplo 
자세한 설명 덕분에 이해했습니다. 감사힙니다!

2023-01-06 16:46 UTC, merged