[Refactor] Tag 데이터 변경된 것으로 적용
depromeet/nyongnyong_iOS pull request #108
Opened 2023-01-02 20:55 UTC by kipsong133

## 📌 배경
- Tag -> TagData(용우님 작업) 으로 변경

## 내용
- 더미 데이터 수정
- 태그 Rows 수에 따른 높이 조절

## 스크린샷 (optional)

- UI 상으로 기존과 다른 점은 없습니다. 
<img width="426" alt="image" src="https://user-images.githubusercontent.com/65879950/210277386-86f2a76e-d692-4615-a29b-00ec237c1886.png">

2023-01-02 22:53 UTC, keeplo requested changes
UserInterface 모듈에서 Domain 모듈은 import 되면 안됩니다ㅠㅠ
DomainInterface 모듈만 import 되어야 합니다.

Domain 내부 구현을 초기화하는건 App.swift 에서만 가능합니다.

[5969d8c](https://github.com/depromeet/ticlemoa-iOS/pull/108/commits/5969d8cf0e715c3d584468daed443baf3d338276) 부분으로 적용되신다면 
빌드도 가능할거라 생각됩니다 ㅠㅠ

EnvironmentObject 같은 경우 제가 실험했을때는

```swift
struct MainView: View {
   // ...
   var body: Scene {
       AView()
          .environmentObject(bObject)
   }
}

struct AView: View {
    @ObservedObject var viewModel: AViewModel
    // ...
}

final class AViewModel: ObservableObject {
    @EnvironmentObject var bObject
}
```
위 코드처럼 적용이 되는걸로 알고 있습니다 혹시 한번 시도해주시고 문제가 있으면
말씀부탁드립니다!

2023-01-02 22:53 UTC, keeplo commented on Targets/UserInterface/Sources/Home/HomeView.swift
> +        HomeView(viewModel: HomeViewModel(model: TagModel()))
UserInterface에 Domain이 의존되지 않기 때문에 해당 코드는 변경이 필요합니다.
`import Domain`은 제거가 필요합니다!
혹시 HomeViewModel 초기화를 HomeViewModel() 형태로 불가능한가요?

2023-01-02 22:53 UTC, keeplo commented on Targets/UserInterface/Sources/Home/HomeViewModel.swift
> +import Domain
혹시 `UIKit`이 필요한 이유를 알 수 있을까요?
SwiftUI 로 대체될수 있다면 `UIKit`과 `Combine` 대신 `SwiftUI ` 만 import 되면 좋을 것 같습니다.

마찬가지로 `Domain`은 import 되면 안되고 `DomainInterface` 만 가능합니다!

2023-01-02 22:53 UTC, keeplo commented on Targets/UserInterface/Sources/MainTab/MainTabView.swift
> +                )
Model을 주입해주는 특별한 이유가 있는지 궁금합니다!

MainTabView 내부에 `@EnvironmentObject var modelContainer: ModelContainer`와
HomeViewModel 내부에 `@EnvironmentObject var modelContainer: ModelContainer`
를 저장프로퍼티로 가지고 있는 방향으로 가면 어떨까요?

2023-01-02 22:53 UTC, keeplo commented on Targets/Domain/Sources/DomainInterface/Sources/Entity/Article.swift
> +}
혹시 이 Commit이 어떻게 생긴건지 알 수 있을까요?

2023-01-02 22:53 UTC, keeplo commented on Targets/Domain/Sources/DomainInterface/Sources/Entity/Tag.swift
> +    var size: CGFloat { get set }
이 부분은 ViewModel에서 처리 될 수 있는 방법은 없을지 고민하면 좋을것 같습니다..

2023-01-02 23:24 UTC, kipsong133 commented on Targets/UserInterface/Sources/Home/HomeView.swift
> +        HomeView(viewModel: HomeViewModel(model: TagModel()))
> 

```swift
final class AViewModel: ObservableObject {
    @EnvironmentObject var bObject
}
```

이 부분에서 bObject 라는 건 도메인에 구성된 모델이 되는건가요?

만약 그러면 모델에 다시 특정 값을 전달하려고 할 때는, 해당 Type 에 맞게 추가해야할텐데,
예를들면, TagModel 에 Tag를 추가하고자 할 때는 해당 타입에 접근이 안되면, 아예 타입을 모르기에 전달자체가 안될 것 같아요.

아니면, 이부분을 제네릭으로 받아서 해보거나, 타입은 접근이 가능하도록 했어야 했나요? 
(제가 이부분을 잘 이해 못한 듯합니다...🥲🥲 도와주세욤)

2023-01-02 23:26 UTC, kipsong133 commented on Targets/UserInterface/Sources/Home/HomeViewModel.swift
> +import Domain
DomainInterface 라는 모듈이 제가 없었는데, 현재 최신 Develop 브랜치에는 있는 상태인가요?

2023-01-02 23:27 UTC, kipsong133 commented on Targets/UserInterface/Sources/MainTab/MainTabView.swift
> +                )
넵~! 그렇게 적용해둘게요! 감사합니다. :)

2023-01-02 23:28 UTC, kipsong133 commented on Targets/Domain/Sources/DomainInterface/Sources/Entity/Article.swift
> +}
잘 모르겠네요..
저도 확인해보고 말씀드릴게요.🥲

2023-01-02 23:30 UTC, kipsong133 commented on Targets/Domain/Sources/DomainInterface/Sources/Entity/Tag.swift
> +    var size: CGFloat { get set }
타입 추론 버그가 나서 일단 하나씩 처리하다보니 이부분을 제가 말씀드린 사항을 준수하지 못했네요 🥲
수정해두겠습니다. 감사합니다 :)

2023-01-03 00:19 UTC, keeplo commented on Targets/UserInterface/Sources/Home/HomeView.swift
> +        HomeView(viewModel: HomeViewModel(model: TagModel()))
현재 저희 앱에서 bObject는 `ModelContainer` 입니다!

다시 특정값을 전달하는 과정에서 두 가지 방법이 있을것 같습니다
`DomainInterface`에 선언된 protocol Tag 부분에 처리를 하거나
타입 내부에 필요 정보만 넘기면 좋을것 같습니다.

Domain - DomainInteface - UserInteface 

이 관계를 유지해서 `DomainInteface` 모듈에서 중재하는 방향으로 가면 좋을것 같아요!

2023-01-03 00:19 UTC, keeplo commented on Targets/Domain/Sources/DomainInterface/Sources/Entity/Tag.swift
> +    var size: CGFloat { get set }
`size`  부분은 같이 고민해보면 좋을것 같습니다!

2023-01-03 08:03 UTC, keeplo commented on Targets/UserInterface/Sources/Home/HomeViewModel.swift
> +import Domain
넵 최신 브런치에서는 접근가능합니다.

2023-01-03 10:48 UTC, closed without merging