[Refactoring] Domain 타입 리팩토링 및 Preview DEBUG 용 타입 생성
depromeet/nyongnyong_iOS pull request #120
Opened 2023-01-05 23:42 UTC by keeplo

## 📌 배경

merged #112 

## 내용
1. 리팩토링 Domain
   > #112 에서 반영하지 못한 오류 및 변경 사항 적용
2. Preview DEBUG 용 타입 생성
   > 모듈이 달라서 Preview에서 사용 못하는 타입 Mock? Fake? (일단 Mock 으로 명명 ㅠㅠ) 데이터 생성

2023-01-06 01:15 UTC, joseph704 approved these changes
고생하셨습니다!

2023-01-06 05:10 UTC, joseph704 requested changes

2023-01-06 05:10 UTC, joseph704 commented on Targets/UserInterface/Sources/ContentView.swift
> +#endif
import DomainInterface가 빠지것 같습니다. 해당 부분에 대해 컴파일 오류가 나는데 확인 부탁드립니다! 

1. MockLoginModel에서 LoginModelProtocol 미준수 
2. MockArticle에서 Article 미준수 
3. HomeViewMdoel.swift 110번째 줄 id파라미터 데이터 타입 Int로 변경해야함

2023-01-06 08:53 UTC, keeplo commented on Targets/UserInterface/Sources/ContentView.swift
> +#endif
전체 타겟으로 빌드하니 못찾아내내요 ㅠㅠ 역시 엑코가 엑코하는..

[commit 50e4368](https://github.com/depromeet/ticlemoa-iOS/pull/120/commits/50e4368e49370e04578cf525f84160c3f8fb2c9b) 추가했습니다
확인 감사합니다!

2023-01-06 11:18 UTC, kipsong133 approved these changes
Publisher 를 잘 사용해보지 않아서 어색한데, 적용해주셔서 감사해요~!

2023-01-07 02:42 UTC, sustainable-git approved these changes
수고하셨습니다!!!

2023-01-07 05:40 UTC, joseph704 approved these changes

2023-01-07 05:40 UTC, merged