[Feature] API Request 및 Response 초안 작성
depromeet/nyongnyong_iOS pull request #125
Opened 2023-01-06 10:21 UTC by keeplo

## 📌 배경

open #123 

## 내용
[Ticlemoa API Server - 스웨거](http://ticlemoa-env-1.eba-6qebrvxf.ap-northeast-2.elasticbeanstalk.com/docs#/Auth/AuthController_oauthLogin) 기준으로

Article 및 BlackList Request 와 Response 추가했습니다.

`-> PR 체이닝으로 TiclemoaAPI 수정과 위 Request 및 Response 테스트 코드까지 추가로 구현하겠습니다.  <-`

2023-01-06 11:15 UTC, kipsong133 commented on Targets/API/Sources/Request/Article/CreateArticleRequest.swift
> +
struct 내부에 body를 정의해서, 코드가 가독성이 좋은 것 같네요~! 배워갑니다 :)

2023-01-06 11:16 UTC, kipsong133 approved these changes
고생하셨습니다

2023-01-07 04:59 UTC, joseph704 approved these changes
가독성 좋은 코드 감사합니다!

2023-01-07 13:11 UTC, joseph704 requested changes

2023-01-07 13:11 UTC, joseph704 commented on Targets/API/Sources/Response/Article/UpdateArticleResponse.swift
>  }
스웨거에서 아티클 업데이트 api에 대한 response 프로퍼티들이 다른것 같습니다! 
테스트 코드에서도 XCTAssertEqual(response!.title, editedTitle)에서 에러나네요

<img width="1397" alt="image" src="https://user-images.githubusercontent.com/35060252/211152084-3a2f7677-2a26-45c9-a023-e84ea0658925.png">

2023-01-07 13:17 UTC, keeplo commented on Targets/API/Sources/Response/Article/UpdateArticleResponse.swift
>  }
<img width="879" alt="image" src="https://user-images.githubusercontent.com/24707229/211152485-f4d0d1ed-af4c-4017-b809-181be2689757.png">
우선 스웨거 업뎃해달라고 하는데 (하셨다고 하는데) 위 사진처럼 8개가 내려옵니다

조금 설명이 부족한데 포스트먼에서 Read 동작으로 수정할 articleId 확인하고 
UnitTest에서 articleId에 정확하게 입력해주어야 합니다..
암 생각없이 C R U D 순서로 C로 생성한 articleId를 읽고 업데이트하고 Delete 하는 순서로 테스트가 진행될 줄 알았는데..
우선순위가 랜덤이더라구요.. 그래서 4개를 동시에 할때는 `articleId`를 다르게 하거나 해야합니다 ㅠㅠ

> 위에 언급한 변경할 `articleId` 넣고 테스트 해도 동작이 실패하는지 확인부탁드려요!

2023-01-07 13:25 UTC, joseph704 approved these changes

2023-01-07 13:45 UTC, merged