[Feature] HomeView UI 리펙토링
depromeet/nyongnyong_iOS pull request #143
Opened 2023-01-08 15:44 UTC by kipsong133

## 📌 배경

- 업데이트 된 UI 추가

## 내용
- Tag 구조체에 맞게 수정
- Folding 값 수정
- Shake Animation 추가
- 아이콘 수정

## 스크린샷 (optional)
- Shake Animation
![Simulator Screen Recording - iPhone 14 Pro - 2023-01-08 at 23 10 34](https://user-images.githubusercontent.com/65879950/211205728-f221efbf-7a8e-4843-a3c7-ed884f308f3c.gif)

- 홈화면
![스크린샷 2023-01-09 00 38 15](https://user-images.githubusercontent.com/65879950/211205746-377f636e-01fa-40c1-8b90-1827d3d27c9d.png)

2023-01-08 22:45 UTC, keeplo requested changes
고생하셨습니다

마지막까지 함께 화이팅입니다..

2023-01-08 22:45 UTC, keeplo commented on Targets/UserInterface/Sources/Home/HomeViewModel.swift
> +}
전에 언급한 부분 반영해주셨군요 👍👍👍

2023-01-08 22:45 UTC, keeplo commented on Targets/UserInterface/Sources/Home/HomeViewModel.swift
> +    }
정렬을 위한 FilterType 부분은 `HomeArticleList` 를 다루는 곳에서 처리하면 어떨까요?
`HomeArticleListViewModel` 에서 `Article` 정렬을 따로 처리해도 좋을것 같다 생각합니다!

2023-01-08 22:45 UTC, keeplo commented on Targets/UserInterface/Sources/MainTab/MainTabView.swift
> +                HomeView(viewModel: HomeViewModel(modelContainer: modelContainer), isNotEmptyArticle: $isNotEmptyArticle)
`isNotEmptyArticle` 부분을 `HomeView` 내부에 `HomeArticleList` 뷰 자체적으로 if 문으로 뷰를 나눠주면 어떨까요?

`HomeView` 에서 특별히 거치지 않아도 처리할 수 있고,  
프로퍼티를 줄일 수 있지 않을까 생각됩니다.

2023-01-08 22:56 UTC, keeplo requested changes
놓친 코멘트 추가했습니다.

2023-01-08 22:56 UTC, keeplo commented on Targets/UserInterface/Sources/Home/HomeViewModel.swift
> +    }
정렬을 위한 FilterType 부분은 `HomeArticleList` 를 다루는 곳에서 처리하면 어떨까요?
`HomeArticleListViewModel` 에서 `Article` 정렬을 따로 처리해도 좋을것 같다 생각합니다!

2023-01-08 22:56 UTC, keeplo commented on Targets/Domain/Sources/Model/TagModel.swift
> +        let readTagRequest = ReadTagRequest(accessToken: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjczMTcyNzQ3LCJleHAiOjE2NzMyNzI3NDcsInN1YiI6IkFDQ0VTU19UT0tFTiJ9.19D_eR5q_4NgDaIYEAQ
현재 PR에서 특별한 동작을 하지 않으니,   
70번 라인은 PR에서 제거해도 괜찮을것 같습니다.  
48번 줄은 discard 되어도 될부분으로 보입니다 ㅠㅠ

> [develop - Article.swift](https://github.com/depromeet/ticlemoa-iOS/blob/develop/Targets/Domain/Sources/Model/ArticleModel.swift) 이 부분은 참고해보시면 구현방식을 구현했습니다.

이번 PR에서 이부분이 빠지고,  
이 후에 TagModel.swift 부분을 전체적으로 구현하는 방향에서 PR 되면 좋을것 같습니다.

2023-01-08 22:56 UTC, keeplo commented on Targets/UserInterface/Sources/Home/HomeView.swift
> +    @Binding var isNotEmptyArticle: Bool
[다른 코멘트](https://github.com/depromeet/ticlemoa-iOS/pull/143/files/ed70c01b6a40d52359200b25abac8560ab81237c#r1064214357)에서 남긴 부분입니다..

제가 MainTab 에서 이 값을 읽어야 하는 이유를 놓친것 같은데 혹시 알려주실수 있을까요?

2023-01-09 12:15 UTC, kipsong133 commented on Targets/UserInterface/Sources/MainTab/MainTabView.swift
> +                HomeView(viewModel: HomeViewModel(modelContainer: modelContainer), isNotEmptyArticle: $isNotEmptyArticle)
현재 MainTabView 에 있는데, 말씀하신 것처럼 하위 View 로 이동해도 좋을 것 같습니다.

HomeView 로 이동시켜두겠습니다!

2023-01-09 12:23 UTC, kipsong133 commented on Targets/UserInterface/Sources/Home/HomeView.swift
> +    @Binding var isNotEmptyArticle: Bool
MainTabView 에서 필요 없어 보이네요.~! 수정했습니다.
HomeView 에 있어야한다고 생각했습니다. 아래 로직때문입니다.
```
1. 태그를 클릭한다.
2. 태그에 맞는 데이터를 서버로부터 가져온다.
3. 서버에서 받아온 데이터를 확인한다. (이 때, 데이터가 있는지 없는지 확인한다.)
3.1 만약 없다면, EmptyView 를 HomeArticleListView 에 보여주도록 데이터를 전파한다.
3.2 데이터가 있다면, 해당 데이터를 ArticleList 에서 보여준다.
```
현재, Tag 에 대해서 데이터 상태관리 구현을 못한 상태라 추측해서 @Binding 을 위치시켰었네요. 설사 받아온다 하더라도, HomeView 면 될 것 같습니다!

2023-01-09 12:31 UTC, kipsong133 commented on Targets/Domain/Sources/Model/TagModel.swift
> +        let readTagRequest = ReadTagRequest(accessToken: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjczMTcyNzQ3LCJleHAiOjE2NzMyNzI3NDcsInN1YiI6IkFDQ0VTU19UT0tFTiJ9.19D_eR5q_4NgDaIYEAQ
넵! 이 부분은 제거할게요~! 링크주신 것도 다시 한번 확인하겠습니다.
LoginUserData 로 싱글톤으로 주입하는 방식으로 이해했는데 맞을까요?

2023-01-09 13:52 UTC, kipsong133 commented on Targets/Domain/Sources/Model/TagModel.swift
> +        let readTagRequest = ReadTagRequest(accessToken: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjczMTcyNzQ3LCJleHAiOjE2NzMyNzI3NDcsInN1YiI6IkFDQ0VTU19UT0tFTiJ9.19D_eR5q_4NgDaIYEAQ
@keeplo 해당 부분 원복해두었습니다~!

2023-01-09 22:24 UTC, Marcorable commented on Targets/UserInterface/Sources/Home/HomeView.swift
> +    @Binding var isNotEmptyArticle: Bool
태그와 연동이 되어서 그랬군요!   
저희 구조가 자리잡기 전에 나온 구현이니 어쩔수 없었네요 ㅠㅠ;;  

저희 구조에서 모델이 공유되는 형태로 구현이 되니,  
태그 클릭들어오면 해당 뷰에서 `ArticleModel`에 fetch 요청해주고,

`HomeArticleListView`는 `ArticleModel`에 의해서 자동으로 갱신되는데,  
데이터가 있으면 보여주고 없으면 EmptyView를 보여주는 형태로 보여주면 좋을것 같아요

2023-01-09 22:28 UTC, keeplo commented on Targets/UserInterface/Sources/MainTab/MainTabView.swift
> +                HomeView(viewModel: HomeViewModel(modelContainer: modelContainer), isNotEmptyArticle: $isNotEmptyArticle)
[fix: 코멘트 반영](https://github.com/depromeet/ticlemoa-iOS/pull/143/commits/fc4c018e5f1963112b54b63444af233bb59c2a72) 부분에 반영이 안되어있습니다 한번 확인 부탁드립니당

[정렬관련](https://github.com/depromeet/ticlemoa-iOS/pull/143/files#r1064214760) 이 부분도 확인 부탁드려요!

2023-01-10 07:07 UTC, joseph704 approved these changes
고생하셨습니다! 용우님 코멘트에 대한 처리 이후 머지 부탁드리겠습니다!

2023-01-10 10:29 UTC, kipsong133 commented on Targets/UserInterface/Sources/Home/HomeViewModel.swift
> +    }
@keeplo 
태그 값 + 정렬에 따라서 아티클 값이 변경되다 보니,  HomeViewModel 에 같이 넣긴 했습니다~!

2023-01-11 12:03 UTC, sustainable-git approved these changes
리펙토링 고생이 많으십니다.

2023-01-12 13:09 UTC, closed without merging