[Feature] 비회원 로그인 API
depromeet/nyongnyong_iOS pull request #154
Opened 2023-01-09 15:23 UTC by kipsong133

## 📌 배경
close #153 

## 내용
- 출시를 위한 비회원 API 기능 구현

## 스크린샷 (optional)
- Token 획득화면
![스크린샷 2023-01-10 00 11 34](https://user-images.githubusercontent.com/65879950/211342546-1a506650-0209-40aa-ac70-9c2fddc957ab.png)

<img width="1127" alt="image" src="https://user-images.githubusercontent.com/65879950/211342678-86d33c09-6943-49bc-b30f-557ddff46749.png">

- 로그인 성공
<img width="534" alt="스크린샷 2023-01-10 00 11 43" src="https://user-images.githubusercontent.com/65879950/211342630-ec779ca3-d4a2-4c78-96d6-8548cde350b1.png">

2023-01-09 23:02 UTC, Marcorable requested changes
고생하셨습니다,

애플이라 ㅠㅠ 한번에 두 로그인 방법을 조사하시느라 고생하셨는데...
우선 출시에 집중하고... 함께 로그인도 완성하도록 노력해요 ㅠㅠ

2023-01-09 23:02 UTC, Marcorable commented on Targets/Domain/Sources/Model/LoginModel.swift
> +    }
```suggestion
    public func requestAccessToken() async -> Bool {
        let request = GetUserTokenRequest()
        let result = await api.request(by: request)
        
        do {
            switch result {
                case .success(let data):
                    let response = try JSONDecoder().decode(GetUserTokenResponse.self, from: data)
                
                LoginUserData.shared = .init(
                    nickName: "",
                    accessToken: response.accessToken,
                    userId: response.userId,
                    mail: ""
                )
                
                return true
                
                case .failure(let error):
                    print(error.description)
                    return false
            }
        } catch {
            print(error.localizedDescription)
            return false
        }
    }
```

data가 올바르게 내려오고 `LoginUserData.shared = .init(..)` 동작을 성공적으로 마친다면,  
관련 토큰과 userId 정보를 UI로 내려줄 필요가 없다고 생각됩니다!   
이후에 통신(Domain)은 모두 `LoginUserData.shared` 에 접근해서 토큰과 userId를 얻을 수 있습니다.   
위 수정을 제안해봅니다

2023-01-09 23:02 UTC, Marcorable commented on Targets/UserInterface/Sources/Login/LoginViewModel.swift
> +
```suggestion
        await modelContainer.loginModel.requestAccessToken()
```
위에 Comment on lines +47 to +73 제안사항이 반영된다면 함께 수정될 부분입니다

2023-01-09 23:02 UTC, keeplo commented on Targets/API/Sources/Request/Login/GetUserTokenRequest.swift
> +public struct GetUserTokenRequest {
별거 아닐 수 있지만 ㅠㅠ  
사용자 타입에 동사형 네이밍이 조금 마음에 걸립니다...  
`UserTokenRequest` - `UserTokenRespons` 같은 형태의 명사형으로 네이밍을 사용하는건 어떨까요?

2023-01-10 01:26 UTC, joseph704 commented on Targets/Domain/Sources/Model/LoginModel.swift
> +    }
동의합니다!

2023-01-10 01:29 UTC, joseph704 commented on Targets/DomainInterface/Sources/Model/LoginModelProtocol.swift
> +    func requestAccessToken() async -> (String, Int)?
```suggestion
    func requestAccessToken() async -> Bool
```
[용우님 LoginModel 메소드 코멘트](https://github.com/depromeet/ticlemoa-iOS/pull/154/files#r1065182733)에 대한 프로토콜 변경점입니다

2023-01-10 04:00 UTC, kipsong133 commented on Targets/UserInterface/Sources/Login/LoginViewModel.swift
> +
@keeplo  아 이렇게 코드 수정을 제안 받을 수 있네요. 피드백 감사합니다~! :)

2023-01-10 04:06 UTC, kipsong133 reviewed
@keeplo  @joseph704  
피드백 주셔서 감사합니다~! 해당 부분 제가 회사에서 Web 에서만 수정했는데, 
수정하면서, 일부 놓친 부분 있으면 그 부분만 양해 부탁드립니다!

2023-01-10 04:10 UTC, keeplo approved these changes
감사합니다!! 고생하셨습니다

2023-01-10 04:19 UTC, merged

2023-01-10 05:03 UTC, joseph704 commented
고생하셨습니다!