[Feature] 프로필 설정 UI 및 마이페이지 UI, Navigation 설정
depromeet/nyongnyong_iOS pull request #28
Opened 2022-12-02 13:04 UTC by sustainable-git

## 📌 배경

close #27

## 내용
- 마이페이지 UI를 조금 더 피그마와 유사하게 변경하였습니다.
- 마이페이지에서 다음 화면인 프로필 설정 화면으로 넘어가는 Navigation을 설정하였습니다.
- 프로필 설정 화면 UI를 그렸습니다.

## 테스트 방법 (optional)
- Preview 확인 혹은 MyPage 화면을 시뮬레이터에서 실행

## 스크린샷 (optional)
<img width=50% height=50% src="https://user-images.githubusercontent.com/81242125/205299072-adf7099d-f949-45c1-b0d1-d7b1785d08d8.gif">

2022-12-05 12:14 UTC, keeplo approved these changes
깔끔하네요! 고생하셨습니다.

2022-12-05 15:40 UTC, joseph704 reviewed
@sustainable-git 
제가 잘 몰라서 그런데, 스유는 피그마에서 offset값 만큼 컴포넌트 사이 거리를 설정하기 애매한가요?
`Text("닉네임")`과 `TextField("닉네임을 입력해주세요.", text: self.$nickname)` offset이 피그마에선 12로 찍히는데 스유에선 따로 12만큼의 offset를 설정하지 않는 것 같아서요.

2022-12-06 00:23 UTC, sustainable-git commented
@joseph704
VStack에 spacing이라는 option이 있고, 이 값을 입력하지 않으면 자동으로 각 componenet마다 16만큼 spacing이 잡힙니다.
제가 이 당시에 값을 보지 못하고 있어서 기본 padding(16)으로 뒀었는데, 디자인 그대로 하는게 맞겠죠..?

2022-12-06 09:07 UTC, joseph704 commented
@sustainable-git 
네 그렇습니다! 아하 값을 보지 못하고 계셨었군요. ㅠㅠ 
깔끔하게 작성해주신 코드 참고 하겠습니다 ㅎㅎ

2022-12-06 14:31 UTC, sustainable-git commented
@joseph704 피드백 반영하여 간격 12p로 변경하였습니다 :)

2022-12-07 12:35 UTC, joseph704 requested changes

2022-12-07 12:35 UTC, joseph704 commented on Targets/UserInterface/Sources/ProfileSettingView.swift
> +            .padding()
@sustainable-git 
[마이페이지_프로필설정_피그마](https://www.figma.com/file/0GiJKsCVFhGzw5hSe3mRVt/6team_Design?node-id=310%3A14043&t=Cej4WBzRnb88i5VE-4)보면  좌우로 패딩 20 되어있는것 같습니다!

2022-12-07 13:05 UTC, sustainable-git commented on Targets/UserInterface/Sources/ProfileSettingView.swift
> +            .padding()
감사합니다. 수정하였습니다. :)

2022-12-09 15:19 UTC, joseph704 requested changes

2022-12-09 15:19 UTC, joseph704 commented on Targets/UserInterface/Sources/MyPageView.swift
> +                        .tint(.init(uiColor: #colorLiteral(red: 0.8012943864, green: 0.7903164029, blue: 0.7607244849, alpha: 1)))
Color.grey3 으로 사용하시면 될 것 같습니다! 
회의 떄 말씀하신 sRGB, dci-p3 차이는 디자이너 분들께 여쭤보고 Asset파일에서 설정시켜 놓겠습니다.

2022-12-09 15:19 UTC, joseph704 commented on Targets/UserInterface/Sources/ProfileSettingView.swift
> +                        .foregroundColor(.init(uiColor: #colorLiteral(red: 0.6036364436, green: 0.5913313031, blue: 0.5479947329, alpha: 1)))
여기는 Color.grey4!

2022-12-09 15:19 UTC, joseph704 commented on Targets/UserInterface/Sources/ProfileSettingView.swift
> +                        .foregroundColor(.init(uiColor: #colorLiteral(red: 0.6036364436, green: 0.5913313031, blue: 0.5479947329, alpha: 1)))
여기두 Color.grey4!

2022-12-09 15:30 UTC, sustainable-git commented on Targets/UserInterface/Sources/MyPageView.swift
> +                        .tint(.init(uiColor: #colorLiteral(red: 0.8012943864, green: 0.7903164029, blue: 0.7607244849, alpha: 1)))
@joseph704 
Xcode Asset에 있는 grey3의 색상(C2BFB5)과 Figma의 grey3의 색상(C1BEB5)이 다릅니다.

|Xcode|Figma|
|:-:|:-:|
|<img src="https://user-images.githubusercontent.com/81242125/206736094-0a85d875-eeb1-4552-8556-53231a4ae9e1.jpeg">|<img src="https://user-images.githubusercontent.com/81242125/206736432-867c6e4d-1836-4695-a2d5-52aa033955bb.jpeg">|

2022-12-09 15:33 UTC, sustainable-git commented on Targets/UserInterface/Sources/ProfileSettingView.swift
> +                        .foregroundColor(.init(uiColor: #colorLiteral(red: 0.6036364436, green: 0.5913313031, blue: 0.5479947329, alpha: 1)))
@joseph704
grey4도 Xcode에는 878578인데, Figma에서는 888579입니다.
|Xcode|Figma|
|:-:|:-:|
|<img src="https://user-images.githubusercontent.com/81242125/206737182-03da1825-c914-4f29-b20c-252931c0bbe9.jpeg">|<img src="https://user-images.githubusercontent.com/81242125/206737114-1ed1c832-b386-42ea-ba1b-a64ac409475b.jpeg">|

2022-12-11 13:02 UTC, joseph704 approved these changes
고생하셨습니다!

2022-12-11 13:57 UTC, merged