[Feature] 계정삭제 Modal UI 구성
depromeet/nyongnyong_iOS pull request #32
Opened 2022-12-02 17:19 UTC by sustainable-git

## 📌 배경

close #28

## 내용
- 계정 삭제 화면의 UI와 마이페이지 화면에서 계정삭제 버튼 기능 동작

## 테스트 방법 (optional)
- 마이페이지 View에서 계정삭제를 누르면 확인 가능합니다.

## 스크린샷 (optional)

|피그마|구현|
|:-:|:-:|
|<img width=360 src="https://user-images.githubusercontent.com/81242125/205348620-ef7673c5-965c-45de-87c8-052ec5f42355.jpeg">|<img width=360 src="https://user-images.githubusercontent.com/81242125/205348532-c44215c3-9335-4fbc-825d-8c0d8e03478b.jpeg">|

2022-12-03 05:18 UTC, keeplo approved these changes
고생하셨습니다!
바로 적용하셨네요;; ㅎㅎ

2022-12-05 13:11 UTC, kipsong133 approved these changes
내용 확인했습니다 ^)^

2022-12-09 15:07 UTC, joseph704 commented on Targets/UserInterface/Sources/MyPageView.swift
> +                .padding(4)
<img width="305" alt="image" src="https://user-images.githubusercontent.com/35060252/206731605-736d3e39-830d-4358-96e9-b555b222580b.png">
Capsule이랑 계정삭제 Text랑 20만큼 offset인데, 
계정삭제 Text가 피그마상으로 애매하게 여백이 있어서 `Capsule에는 .padding(18)`로 하고 `계정삭제 Text에는 .padding(4)`로 지정하신건가요?

2022-12-10 00:34 UTC, joseph704 requested changes

2022-12-10 00:34 UTC, joseph704 commented on Targets/UserInterface/Sources/MyPageView.swift
> +                .padding(.horizontal, 36)
<img width="305" alt="image" src="https://user-images.githubusercontent.com/35060252/206732266-4f2df72f-1060-462d-b745-5afc2b76f713.png">
계정삭제 Text에 여백이 있어서 애매하지만, 26정도 Offset이 지정되어 있는것 같아요!

2022-12-10 00:34 UTC, joseph704 commented on Targets/UserInterface/Sources/MyPageView.swift
> +            .padding(36)
![image](https://user-images.githubusercontent.com/35060252/206818865-a2b847bc-dec3-40f9-9f49-cd967c2a9ed9.png)
이미지랑 정말로 계정을 삭제하시겠어요? offset도 24로 되어있는걸로 보입니다!

2022-12-10 00:34 UTC, joseph704 commented on Targets/UserInterface/Sources/MyPageView.swift
> +                            .foregroundColor(.init(uiColor: #colorLiteral(red: 0.9058823529, green: 0.8901960784, blue: 0.862745098, alpha: 1)))
grey2Line, 색상값 다른것은 제가 이슈랑 같이 pr 올리겠습니다!

2022-12-10 16:39 UTC, sustainable-git commented on Targets/UserInterface/Sources/MyPageView.swift
> +                .padding(.horizontal, 36)
계정삭제 하단 padding은 Text에서 적용되었습니다.
Spacer()의 padding은 좌 우 padding입니다.

2022-12-11 12:58 UTC, joseph704 approved these changes
고생하셨습니다!

2022-12-11 13:58 UTC, merged