[Feature] MainTabView 구성 및 기타 컴포넌트 추가
depromeet/nyongnyong_iOS pull request #38
Opened 2022-12-06 13:54 UTC by kipsong133

📌 배경

close https://github.com/depromeet/nyongnyong_iOS/pull/37

내용

MainTabView 구성 및 기타 UI 컴포넌트 추가

<img width="535" alt="image" src="https://user-images.githubusercontent.com/65879950/205930438-ac6504f7-4fd5-4e64-8be7-a9d00bbcbc77.png">

<img width="535" alt="image" src="https://user-images.githubusercontent.com/65879950/205930487-6dd11977-2579-40d5-a004-5aa613b5ffbe.png">

2022-12-06 14:38 UTC, sustainable-git requested changes
PR 제목 다시 확인해 주실 수 있으실까요?

2022-12-06 15:14 UTC, keeplo requested changes

2022-12-06 15:14 UTC, Marcorable commented on Targets/Ticlemoa/Sources/TiclemoaApp.swift
> +            MainTabView()
`TiclemoaApp.swift` 파일이 예제 코드에서 그대로 전달된거 같습니다!

`TiclemoaApp.swift` 파일은 최상위 타겟이고 `MainTabView` 는 UserInterface 타겟이여서 
`public` 아닌 현재 코드에서는 에러가 날 것 같습니다!

기존에 존재하던 `public struct ContentView: View` 파일과 인스턴스를 `TiclemoaApp.swift` 파일에 유지하고
`ContentView` 내부에 `MainTabView` 인스턴스를 품는 형태로 가는 방향을 제안해봅니다!
`ContentView`만 외부에 접근하고 `MainTabView`는 생성될 다른 View 들과 Internal로 통일성을 줄수 있을 것 같아요!

> 저는 SwiftUI 에서 `ContentView` 가 UIKit 네비컨트롤러의 rootViewController 처럼 
> 상징적인 의미로 Root View 로 쓰이면 좋을 것 같다고 생각하는데..
> Apple Developer Tutorial 이나 해외 자료에서 `ContentView`가 살아있어서 이렇게 생각하게 됐습니다 
> 다른 분들 (@sustainable-git @joseph704) 의견도 궁금합니다!

2022-12-06 15:49 UTC, sustainable-git commented on Targets/Ticlemoa/Sources/TiclemoaApp.swift
> +            MainTabView()
오... ContentView를 그대로 사용한다는게 굉장히 신선한 아이디어네요.
하지만 MainTabView에 한 표 합니다. :)

[hackingwithswift](https://www.hackingwithswift.com/forums/100-days-of-swiftui/your-thoughts-renaming-contentview/10208)
<img src="https://user-images.githubusercontent.com/81242125/205957823-4c9e1eac-9c76-4ae4-a51f-5d79a1f1ab22.jpeg">

2022-12-06 23:00 UTC, keeplo commented on Targets/Ticlemoa/Sources/TiclemoaApp.swift
> +            MainTabView()
링크까지 주셔서 감사합니다. Discussion 참여자가 좀 더 많았으면 좋았을텐데 3명 밖에 없어서 좀 아쉽네요..

`Naming` 에 대해서는 변경에는 큰 거부감이 없어서 동의할 수 있을것 같은데...
UserInterface Views 중 유일한 외부 접근 View로써 역할을 충실했으면 하는 부분은 한번 더 고민해주면 좋을 것 같아요
```swift
// Main Target - Ticlemoa
@main
struct TiclemoaApp: App {
	var body: some Scene {
		WindowGroup {
			A() // 외부 접근 View 역할 부여한 네이밍
		}
	}
}

// Sub Target - UserInterface - A.swift
public struct A: View {
	var body: some View {
		MainTabView()
	}
}

// Sub Target - UserInterface - MainTabView.swift
internal struct MainTabView: View {
	var body: some View {
		// ...
	}
}

```
> ps 재웅님 혹시 애플아카데미에서도 이런 이슈가 있나 궁금합니다! ㅎㅎ

2022-12-07 01:51 UTC, joseph704 commented on Targets/Ticlemoa/Sources/TiclemoaApp.swift
> +            MainTabView()
@keeplo 
ContenView 네이밍(ex.RootView)만 바꾸고, @keeplo 님 말씀처럼 Ticlemoa 최상위 모듈이랑 UserInterface 모듈을 잇는 역할로 이용하는 데에 찬성합니다!

2022-12-07 11:56 UTC, kipsong133 commented on Targets/Ticlemoa/Sources/TiclemoaApp.swift
> +            MainTabView()
확인해볼게요~!
감사합니다.

2022-12-07 11:57 UTC, kipsong133 commented
> PR 제목 다시 확인해 주실 수 있으실까요?

앗. 수정해서 다시 올릴게요!

2022-12-10 06:29 UTC, keeplo approved these changes
수정 확인했습니다

2022-12-10 06:33 UTC, joseph704 approved these changes

2022-12-10 06:36 UTC, merged