[Feature] 링크 추가 UI 구성
depromeet/nyongnyong_iOS pull request #45
Opened 2022-12-12 05:40 UTC by joseph704

## 📌 배경

close #26 

## 내용
- 링크 추가 UI 구성
- 여백 클릭 시, 키보드 내리기 위한 함수 추가

2022-12-12 10:43 UTC, kipsong133 approved these changes
이미지 추가하신 부분이랑, 키보드 관련 제스처 유용하게 사용할게요~! 
내용 확인했습니다!

2022-12-12 13:17 UTC, Marcorable requested changes
화면에 뭐가 진짜 많아서 복잡 했을텐데 고생하셨습니다.
키보드 내리기 Extension 도 정말 감사합니당

2022-12-12 13:17 UTC, Marcorable commented on Targets/UserInterface/Sources/LinkAdd/View/LinkAddView.swift
> +    case naviBar
진짜 별거 아니긴 한데.. 질문입니다!
탭바 중앙에 버튼으로 들어온 경우인데 네비로 지으신 이유가 혹시 있으신가요?
NavigationLink로 들어와서 일까요?

2022-12-12 13:17 UTC, keeplo commented on Targets/UserInterface/Sources/LinkAdd/View/LinkAddView.swift
> +struct LinkAddView: View {
타입 네이밍에 동사형은 조금 피하면 좋을것 같아요

프리뷰처럼 `Adding`을 추천드려봅니다...

2022-12-12 13:17 UTC, keeplo commented on Targets/UserInterface/Sources/LinkAdd/View/LinkAddView.swift
> +}
워낙 한 화면에 구성되는 게 많아서 어쩔 수 없는 부분이긴한데..

연산 프로퍼티로 단락을 나눠서
`body` 에 View 구성을 파악하기 쉽게 나누면 어떨까요?
코드 가독성이 쪼끔 더 좋아지지 않을까 생각합니다!

2022-12-12 14:51 UTC, joseph704 commented on Targets/UserInterface/Sources/LinkAdd/View/LinkAddView.swift
> +    case naviBar
@keeplo 
피그마에 제시된대로 작명하였습니다. 추후에 디자이너 분들과의 공통 용어로 쓰기 좋도록 그대로 이행해봤습니다 ㅎㅎ
<img width="429" alt="image" src="https://user-images.githubusercontent.com/35060252/207075813-2a29f2e8-e739-4d27-a847-2c44eaf8e4af.png">

2022-12-12 14:54 UTC, joseph704 commented on Targets/UserInterface/Sources/LinkAdd/View/LinkAddView.swift
> +struct LinkAddView: View {
앗.. 듣고보니 그러네요.. 수정하도록 하겠습니다. 감사합니다! (영어 스타 강사의 짬바란..)

2022-12-12 14:59 UTC, joseph704 commented on Targets/UserInterface/Sources/LinkAdd/View/LinkAddView.swift
> +}
@keeplo 
감사합니다. 한번 나눠 보겠습니다! 

예를들어 아래 표시한 빨간 원 마다 이해하기 쉬운 View(`ex.첫번째 빨간 원 == InsertingLinkView`)로 묶어서 body에 두면 나을 것 같다는 말씀이시죠?

<img width="346" alt="image" src="https://user-images.githubusercontent.com/35060252/207077404-c0d0de25-83db-4e84-b757-03de05cee1b8.png">

2022-12-13 04:43 UTC, keeplo commented on Targets/UserInterface/Sources/LinkAdd/View/LinkAddView.swift
> +    case naviBar
답변감사합니다!

2022-12-13 04:43 UTC, keeplo commented on Targets/UserInterface/Sources/LinkAdd/View/LinkAddView.swift
> +struct LinkAddView: View {
그쵸 서당개 1년 입니다 ㅎ

2022-12-13 04:44 UTC, keeplo commented on Targets/UserInterface/Sources/LinkAdd/View/LinkAddView.swift
> +}
넵 말씀해주신 방향이 맞습니다!

2022-12-13 12:25 UTC, sustainable-git commented on Targets/UserInterface/Sources/Home/HomeView.swift
> -        NavigationView {
NavigationView가 없어도 되나요?
HomeView에서 ProfileView로 넘어갈 때 필요할것 같습니다.

2022-12-13 14:56 UTC, joseph704 commented on Targets/UserInterface/Sources/Home/HomeView.swift
> -        NavigationView {
@sustainable-git 
HomeView 뿐만 아니라 다른곳에서 사용해야할 것 같아서, HomeView의 상위뷰인 MainTabView에 NavigationView추가해 두었습니다!

2022-12-13 14:57 UTC, joseph704 commented on Targets/UserInterface/Sources/MainTab/MainTabView.swift
> +        NavigationView {
@sustainable-git 
NavigationView 여기에 추가해 두었습니다!

2022-12-13 15:50 UTC, joseph704 commented on Targets/UserInterface/Sources/LinkAdd/View/LinkAddView.swift
> +}
@keeplo 
해당 부분 수정했습니다. 확인부탁드립니다.

2022-12-13 15:50 UTC, joseph704 commented on Targets/UserInterface/Sources/LinkAdd/View/LinkAddView.swift
> +struct LinkAddView: View {
@keeplo 
해당 부분 수정했습니다. 확인부탁드립니다!

2022-12-15 08:21 UTC, keeplo approved these changes
늦어서 죄송해용 고생하셨습니다!

2022-12-15 08:28 UTC, merged