[Feature] LoginView, HomeView 정렬 기능, Font System 추가
depromeet/nyongnyong_iOS pull request #46
Opened 2022-12-12 13:30 UTC by kipsong133

## 📌 배경

close #39 
close #41 
close #18 

## 내용

- LoginView UI 구성
- HomeView 날짜순 정렬 기능
- FontSystem
(참고로 아이콘은 TestFlight 제출을 위해, Dummy 이미지로 추가했습니다.)

## 테스트 방법 (optional)

- TestFlight 앱 실행

## 스크린샷 (optional)

<img width="475" alt="image" src="https://user-images.githubusercontent.com/65879950/207056792-1dfa962d-0607-4c73-a05f-abf9a04c22b2.png">

<img width="475" alt="image" src="https://user-images.githubusercontent.com/65879950/207056828-b41f7ccf-4926-4bfe-adfe-ab77783a59ac.png">

2022-12-12 14:12 UTC, keeplo requested changes
잔잔바리로 질문과 제안을 코멘트로 몇가지 남겼습니다..

왜 안되지? 10번 외치고 정복.. 멋집니다.. 고생하셨습니다...
폰트 시스템... 너무 고생많으셨어요..

2022-12-12 14:12 UTC, keeplo commented on Targets/UserInterface/Sources/Home/HomeView.swift
> +    @StateObject var viewModel = HomeViewModel()
`@StateObject` 를 사용하신 이유가 있으신지 궁금합니다!

2022-12-12 14:12 UTC, keeplo commented on Targets/UserInterface/Sources/Home/HomeView.swift
>                  })
mainBody 네이밍이 불 필요하다고 느껴집니다..

`ToobarItemGroup` 별로 연산프로퍼티로 분리하고 (`@ViewBuilder`) 
-> 주석 대신 프로퍼티 네이밍으로 용도 전달하는 형태로 구성하면 어떨까 제안해봅니다!

2022-12-12 14:12 UTC, keeplo commented on Targets/UserInterface/Sources/Login/LoginView.swift
> +    }
이 부분도 저는 위에 언급한 `mainBody()`와 같이 불필요한 구성이란 생각을 가지고 있는데..

혹시 이렇게 구성하신 방향이 어떤 의도인지 궁금합니다!

2022-12-12 22:58 UTC, kipsong133 commented on Targets/UserInterface/Sources/Home/HomeView.swift
> +    @StateObject var viewModel = HomeViewModel()
StateObject 는 화면을 다시 그릴 때, 변경된 부분 외에 다시 그리지 않아서 사용하긴 하는데,
혹시 ObservedObject 랑 StateObject 중 선택에 대한 이유가 궁금하신 건가요? 혹은 다른이유일까요!?

2022-12-12 22:59 UTC, kipsong133 commented on Targets/UserInterface/Sources/Home/HomeView.swift
>                  })
넵. 함수보다는 연산프로퍼티로 사용해보죠~!

2022-12-12 23:01 UTC, kipsong133 commented on Targets/UserInterface/Sources/Login/LoginView.swift
> +    }
UI 를 나눌 때, 3 가지 정도로 그냥 나누고 싶었습니다.
1. 화면 전체에 적용되는 UI -> mainBody() 호출부에 추가
2. 화면의 위치에 따른 배치 -> mainBody 바로 하위에 추가
3. 각각의 세부구현 -> View 로 생성 혹은, 연산 프로퍼티

사실 이건 저만의 기준으로 작성한거라 의견 주시면, 감사하겠습니다 ~! : )

2022-12-13 00:19 UTC, keeplo commented on Targets/UserInterface/Sources/Home/HomeView.swift
> +    @StateObject var viewModel = HomeViewModel()
말씀해주신 두 가지 중 선택한 이유가 궁금했습니다!

탭바 변동만 생각하고 View가 특별히 init 되지 않을꺼 같다고 생각하고 질문드렸는데..
지금 다시 생각해보니.. HomeView나 CommunityView 하위뷰에서 확실히 View 변동이 생기고 init 될거 같아요..

답변 감사합니다!

2022-12-13 00:27 UTC, keeplo commented on Targets/UserInterface/Sources/Login/LoginView.swift
> +    }
[위 질문](https://github.com/depromeet/nyongnyong_iOS/pull/46#discussion_r1045868528) 과 엮인것 같네요..
> 약간 야곰 가르침 탓에 습관적인 부분인데..
> 함수/변수 네이밍 + 인자 레이블 등을 이용해서 최대한 코드를 가독성 좋게 만들고
> 주석은 최소화 (기능 세부사항)
> 스타일을 지향하는 편이여서 위처럼 의견을 드려봤습니다.

확실히 스타일이라 느껴지는 부분인거 같아서..

약간 저는 우성님이 말씀해주신 상황에서 생각에

1. 화면 전체에 적용되는 UI -> 부모 뷰에서 호출/할당 부에서 ViewModifier 지정 
       + NavigationView 등 특수한 경우 전체 ViewModifier body 에 적용
2. 화면의 위치에 따른 배치 -> body에 배치
3. 각각의 세부구현 -> View 로 생성 혹은, 연산 프로퍼티

형태로 작성 했었거든요.

맨날.. 소환하는 것 같은데.. 죄송합니다 ㅎㅎㅎ
@joseph704 @sustainable-git 

함께 고민해보고 Ticlemoa 프로젝트에서 스타일을 맞추면 어떨까 생각합니다!

2022-12-13 00:30 UTC, keeplo commented on Targets/UserInterface/Sources/Home/HomeView.swift
>                  })
[아래 답변](https://github.com/depromeet/nyongnyong_iOS/pull/46#discussion_r1046546633)과 엮어서 
같이 고민해보고 스타일을 정하면 좋을 것 같습니다!

2022-12-15 07:16 UTC, kipsong133 commented on Targets/UserInterface/Sources/Login/LoginView.swift
> +    }
혹시 이부분 예제코드가 있을까요? 제가 어떤식으로 할지 잘 그림이 안그려집니다.ㅠㅠ

2022-12-15 13:28 UTC, sustainable-git commented on Targets/UserInterface/Sources/Login/LoginView.swift
> +    }
@keeplo 

저는 주로 fileprivate struct를 만드는 편이어서, 함수 형태로 UI를 작성하는게 새롭긴 합니다.
View가 함수 형태로 만들어진다면 UI 구성과 Action의 구분요소가 하나 줄어드니 가독성이 떨어지지 않나 생각이 들긴 하네요.

2022-12-15 13:29 UTC, sustainable-git commented on Targets/UserInterface/Sources/ContentView.swift
> +        let appKey = "a864acaf7534a2c1a627e21d352d2e49"
api key를 가릴 방법이 필요할것 같습니다.

2022-12-15 13:35 UTC, sustainable-git commented on Targets/UserInterface/Sources/Login/LoginView.swift
> +    }
@keeplo 

저는 재사용할 일이 있지 않으면 `var body` 구문에 다 만드는 편이라
확실히 mainBody() 구문이 불필요하게 느껴지긴 하네요.

2022-12-15 13:51 UTC, kipsong133 commented on Targets/UserInterface/Sources/ContentView.swift
> +        let appKey = "a864acaf7534a2c1a627e21d352d2e49"
앱 배포 단계에서는 "Config.xcconfig" 을 활용해서 Info.plist 에서 접근하도록 하게하려고해요.

물론 gitIgnore 에 해당 파일은 추가해서, 따로 전달드리는 식으로 해야할 것 같구요!

2022-12-20 12:22 UTC, joseph704 approved these changes

2022-12-20 15:21 UTC, joseph704 commented
확인했습니다. 고생하셨습니다!

2022-12-26 09:01 UTC, keeplo approved these changes
고생하셨습니다

2022-12-26 09:01 UTC, keeplo commented on Targets/UserInterface/Sources/Home/HomeArticle/Article.swift
> +import UIKit
혹시 UIKit import가 안되면 에러가 발생할까요?

2022-12-27 12:01 UTC, kipsong133 commented on Targets/UserInterface/Sources/Home/HomeArticle/Article.swift
> +import UIKit
다른 작업하다가 지우지 못했나봅니다~! 감사합니다!

2022-12-30 05:46 UTC, kipsong133 commented
Rebase 로 몇 번이고 해봤는데, 각각의 PR들이 컴파일에러가 많아서, 소통이 더어려워 질 수도 있을 것 같습니다.
제가 급하다는 핑계로 너무 커뮤니케이션 부분 신경안쓰고 코드 쓴 것 같습니다 ㅠㅠ.

이번만 Squash 하겠습니다~!

2022-12-30 05:52 UTC, merged