[Feature] Ticlemoa CustomAlert 구성하기
depromeet/nyongnyong_iOS pull request #48
Opened 2022-12-12 15:31 UTC by keeplo

## 📌 배경

close #47 

## 내용
* 어떤 뷰에서든 최상위 뷰로 얼럿 Present
* ViewModifier로 구현가능

## 테스트 방법 (optional)
* style `.inputText`
<img width="353" alt="스크린샷 2022-12-12 오후 11 53 02" src="https://user-images.githubusercontent.com/24707229/207085509-54b13aa3-a3ec-457a-bed9-b371bf5ddc13.png">
* style `.confirm(String)`  
<img width="451" alt="스크린샷 2022-12-12 오후 11 46 32" src="https://user-images.githubusercontent.com/24707229/207085551-19df697e-5ebd-4956-9ef6-2286eda811f0.png">

## 스크린샷 (optional)
|새 태그 만들기|확인|
|:-:|:-:|
| ![Simulator Screen Shot - iPhone 12 (iOS 16 0) - 2022-12-12 at 23 52 50](https://user-images.githubusercontent.com/24707229/207085599-24735a37-e437-4fcf-8bb7-eef83aa00de6.png) | ![Simulator Screen Shot - iPhone 12 (iOS 16 0) - 2022-12-12 at 23 52 20](https://user-images.githubusercontent.com/24707229/207085650-f260e434-7d46-43f5-9352-299f3aa25e95.png) |

2022-12-15 13:00 UTC, kipsong133 approved these changes
내용 확인했습니다. Enum 으로 깔끔하게 구성되서 보기 좋네요~!

2022-12-15 13:31 UTC, sustainable-git approved these changes
components를 property 형태로 만드시는군요! 새롭습니다. :)

2022-12-15 13:31 UTC, sustainable-git commented on Targets/UserInterface/Sources/Utils/Components/TiclemoaAlert.swift
> +    @ViewBuilder
뷰빌더 사용 너무 멋져요!

2022-12-15 14:11 UTC, sustainable-git requested changes
현재 커밋이 4개인데, 하나로 만들 수 없을까요?

2022-12-16 08:28 UTC, keeplo commented
> 

음.. 경험이 없어서 그런데 혹시 어떤 키워드로 적용하면.. 
할 수 있을까요?

2022-12-16 08:55 UTC, keeplo commented
> 현재 커밋이 4개인데, 하나로 만들 수 없을까요?

적용했습니다!

force-push 살떨리네요..

2022-12-17 06:18 UTC, sustainable-git approved these changes

2022-12-20 12:32 UTC, joseph704 approved these changes
깔끔하네요 ㅎㅎ 고생하셨습니다!

2022-12-22 10:34 UTC, merged