[Refactor] 마이페이지 UI 업데이트
depromeet/nyongnyong_iOS pull request #62
Opened 2022-12-17 09:16 UTC by sustainable-git

## 📌 배경

close #61

## 내용
- 마이페이지 UI를 조금 더 피그마와 유사하게 변경하였습니다.
  - 배경화면 적용
  - 아이콘 변경
  - padding 조절
  - default 아이콘
- 네비게이션바는 만들어지는 대로 변경하겠습니다.

## 테스트 방법 (optional)
- Mypage 화면 실행

## 스크린샷 (optional)

|피그마|구현|
|:-:|:-:|
|<img width=360 src="https://user-images.githubusercontent.com/81242125/208234765-0d59b08e-4462-411f-aeb9-e9bb454c05c4.jpg">|<img width=360 src="https://user-images.githubusercontent.com/81242125/208234761-dab4c5d5-bfde-4907-b6e2-c3c1103b6f36.png">|

2022-12-18 08:18 UTC, kipsong133 approved these changes

2022-12-19 09:52 UTC, keeplo approved these changes
고생하셨습니다!

깔끔하게 잘적용 되었네요!

2022-12-19 09:52 UTC, keeplo commented on Targets/UserInterface/Sources/MyPage/MyPageView.swift
> +            .padding(.horizontal, 20)
경험적인 질문이 한가지 있습니다!

개발 과정에서는 디자인 초안 기기설정에 맞춰서 이렇게 구현 하는데
나중에 SwiftUI로 View 구성할때 기기대응은 주로 어떻게 하셨는지 궁금합니다!

2022-12-20 04:35 UTC, sustainable-git commented on Targets/UserInterface/Sources/MyPage/MyPageView.swift
> +            .padding(.horizontal, 20)
@keeplo 
제가 질문을 잘 이해를 못 한 걸까요..? ㅠㅠ 이렇게 짜면 기기대응이 되어 있다고 생각했습니다.
혹시 기기 크기가 세로로 많이 차이나게 되어 세로 길이가 차이가 나면 어떻게 되냐는 질문이라면, 저는 모든 View에 ScrollView를 넣어야 한다고 생각하는 편이에요!
아래처럼 하면 사이즈가 커질 때만 스크롤이 가능한 뷰를 구성할 수 있다고 알고 있어요!

[SwiftUI: Make ScrollView scrollable only if it exceeds the height of the screen](https://stackoverflow.com/questions/62463142/swiftui-make-scrollview-scrollable-only-if-it-exceeds-the-height-of-the-screen)

2022-12-20 04:39 UTC, keeplo commented on Targets/UserInterface/Sources/MyPage/MyPageView.swift
> +            .padding(.horizontal, 20)
조금 질문이 명료하지 못했는데..

약간 버튼을 예로 들어서   

해상도에 같은 비율로 버튼이 커지는 형태로 하시는지..  
버튼 크기는 그대로인 상태로 각 컴포넌트간에 적절한 거리를 비율로 가지는 형태로 하시는지..  

그런 방향이 궁금했습니다.

2022-12-20 04:40 UTC, joseph704 requested changes
고생많으셨습니다! 색상만 바꿔주시면 될것같습니다!

2022-12-20 04:40 UTC, joseph704 commented on Targets/UserInterface/Sources/MyPage/MyPageView.swift
>                              .foregroundColor(.black)
.black로 하신부분들 .ticlemoaBlack로 변경해야할 것 같습니다!

2022-12-20 08:14 UTC, sustainable-git commented on Targets/UserInterface/Sources/MyPage/MyPageView.swift
>                              .foregroundColor(.black)
모든 까만색이 그냥 까만 색이 아니었군요...

2022-12-20 10:30 UTC, sustainable-git commented on Targets/UserInterface/Sources/MyPage/MyPageView.swift
> +            .padding(.horizontal, 20)
@keeplo 
알려주신 두 방법 모두 사용했던것 같습니다.
지금처럼 좌 우 padding이 일정했던 경우가 많아서, padding을 제외한 크기만큼 버튼이 항상 커졌던것 같아요.

2022-12-20 10:31 UTC, joseph704 commented on Targets/UserInterface/Sources/MyPage/MyPageView.swift
>                              .foregroundColor(.black)
제눈엔 다 똑같아 보이는... ㅋㅋㅋㅋ

2022-12-20 10:35 UTC, sustainable-git commented on Targets/UserInterface/Sources/MyPage/MyPageView.swift
>                              .foregroundColor(.black)
수정했습니다!

2022-12-20 15:22 UTC, joseph704 approved these changes
고생하셨습니다!

2022-12-22 09:53 UTC, keeplo commented on Targets/UserInterface/Sources/MyPage/MyPageView.swift
> +            .padding(.horizontal, 20)
@sustainable-git  

그렇군요! 음... 사실 어찌보면.. 정하기 나름인 부분이거나   
디자인 측면으로 결정될 사항인데..   
그래도 답변 감사합니다!

2022-12-22 10:38 UTC, merged