[Refactor] 모듈 의존관계 및 의존성 주입 구조 설계
depromeet/nyongnyong_iOS pull request #72
Opened 2022-12-20 22:59 UTC by keeplo

## 📌 배경

#54 #55
close #71

## 내용
* 각 ViewModel 마다 `import Domain` 되는 구현 형태
   > [참고 자료 - let us: Go! 2022 가을 - 느슨한 결합을 느껴보자 / clyne.kim 님](https://www.youtube.com/watch?v=z62qp-owiSk&list=PL03rJBlpwTaDcTTNVMETmglJZpM-GuPm3&index=3) 참고해서 모듈 Interface 개념 적용
* 프로토콜 추상화 개체가 `.environmentObject` 를 통해 전달이 안되는 이슈
   > [참고자료 -Why You Shouldn’t Use @EnvironmentObject in SwiftUI](https://betterprogramming.pub/why-you-shouldnt-use-environmentobject-in-swiftui-a527d5c2bd) 를 통해서     
   > `.environmentObject`는 리스코프 치환원칙을 위반 한다는 걸 인지해서  `ModelContainer` 타입을 생성해서 해결했습니다.

## 스크린샷
|TiclemoaApp|HomeViewModel|
|:--:|:--:|
|<img width="768" alt="image" src="https://user-images.githubusercontent.com/24707229/208691402-bb6d984f-a6a2-4cfd-a35f-e2a5aa00ca44.png">|<img width="766" alt="image" src="https://user-images.githubusercontent.com/24707229/208689199-b6adba45-9c9f-41f6-9e77-ec65d7ce5c90.png">|
|`ModelContainer`를 `.environmentObject` 이용해서 전달|위 이미지처럼 ViewModel은 Model에 접근|

2022-12-22 14:56 UTC, joseph704 requested changes
고생하셨습니다!

2022-12-22 14:56 UTC, joseph704 commented on Targets/API/Sources/HTTPMethod.swift
> +            request.httpMethod = request.httpMethod
```suggestion
            request.httpMethod = httpMethod
```

지난번 pr에서 언급했던 부분입니다!

2022-12-26 14:55 UTC, sustainable-git reviewed
잘 봤습니다.
혹시 Domain interface가 굳이 있어야 하는 이유를 알 수 있을까요?
Domain은 가장 핵심. 굳이 의존성을 역전하기 위해 protocol을 사용할 필요가 없을것 같아서요.

2022-12-26 15:50 UTC, kipsong133 approved these changes

2022-12-26 23:22 UTC, keeplo commented
> 잘 봤습니다.
> 혹시 Domain interface가 굳이 있어야 하는 이유를 알 수 있을까요?
> Domain은 가장 핵심. 굳이 의존성을 역전하기 위해 protocol을 사용할 필요가 없을것 같아서요.

어려운 질문이네요.. 

우선 가장 큰 목표는 `UserInterface` 모듈과 `Domain` 모듈의 **의존성 분리**입니다.   
이전 코드와 달리 ViewModel 내부에서 `import Domain` 로 직접 접근을 피할 수 있습니다.

의존 역전을 굳이 하는 부분에 대해서는... 답변하기가 좀 어려운 부분이 있어요..
말씀하신것처럼 굳이 넣지 않아도 되는 부분이라..

SOLID 원칙이 코드가 작동하는데 있어서 굳이 필요하지 않은 부분이지만... ㅠㅠ    
객체간의 `결합도` 높히고 `응집도`는 낮춰서 `유지보수` 효율성을 높이는게 객체지향 패러다임에서 목표이다보니..  
Tuist - 모듈화에 이어져서 자연스럽게 적용하게 되었습니다.

구현 단계에서 인터페이스 수정 -> 구현체 수정처럼 단계가 늘어나는 단점도 있지만,  
인터페이스 결정 -> 구현체 / 호출부 분리 구현이 가능한 장점도 있다고 생각합니다.

> 빠르게 구현해야하는 저희 환경에서 좀 무거운 환경을 구축한 것 같아서 좀 죄송한 마음을 가지고 있습니다 ㅠㅠ   
> 저희 동아리 활동이 끝나더라도 이 부분에 대해서는 스터디나 저희 프로젝트에 적용하는등 공부하는것도 좋을 것 같습니다!

* [오브젝트](http://www.yes24.com/Product/Goods/74219491), [엘레강트 오브젝트](http://www.yes24.com/Product/Goods/96193044)

2022-12-27 02:10 UTC, sustainable-git commented
@keeplo 

`import Domain`과 `import DomainInterface`가 어떤 큰 차이가 있는지 잘 모르겠어요.
iOS Clean Architecture를 보면 ViewModel이 Model을 참조할 때 protocol로 참조하지 않고 객체를 그대로 참조합니다.
[iOS Clean Architecture-MVVM](https://github.com/kudoleh/iOS-Clean-Architecture-MVVM/blob/20edb84d7235dcad0bd1266614b1a46f71b607f2/ExampleMVVM/Presentation/MoviesScene/MoviesList/ViewModel/MoviesListViewModel.swift#L49)
그래서 `import Domain`을 하는게 맞지 않을까 하는 생각을 가지고 있습니다.
그러나 용우님이 Hexagonal Architecture를 염두해두고 만드셨다면 `import DomainInterface`가 의미가 있을것 같긴 합니다.

> 구현 단계에서 인터페이스 수정 -> 구현체 수정처럼 단계가 늘어나는 단점도 있지만,
> 인터페이스 결정 -> 구현체 / 호출부 분리 구현이 가능한 장점도 있다고 생각합니다.

위의 말씀에서 구현체 / 호출부 분리 구현이 어떤 의미가 있을까요?
분리 구현이 서로 다른 사람이 각각 ViewModel과 Domain을 따로 개발하고 protocol로 대화한다는 의미라면 이 방법에 찬성합니다.

2022-12-27 04:51 UTC, keeplo commented
> @keeplo
> 
> `import Domain`과 `import DomainInterface`가 어떤 큰 차이가 있는지 잘 모르겠어요. iOS Clean Architecture를 보면 ViewModel이 Model을 참조할 때 protocol로 참조하지 않고 객체를 그대로 참조합니다. [iOS Clean Architecture-MVVM](https://github.com/kudoleh/iOS-Clean-Architecture-MVVM/blob/20edb84d7235dcad0bd1266614b1a46f71b607f2/ExampleMVVM/Presentation/MoviesScene/MoviesList/ViewModel/MoviesListViewModel.swift#L49) 그래서 `import Domain`을 하는게 맞지 않을까 하는 생각을 가지고 있습니다. 그러나 용우님이 Hexagonal Architecture를 염두해두고 만드셨다면 `import DomainInterface`가 의미가 있을것 같긴 합니다.
> 
> > 구현 단계에서 인터페이스 수정 -> 구현체 수정처럼 단계가 늘어나는 단점도 있지만,
> > 인터페이스 결정 -> 구현체 / 호출부 분리 구현이 가능한 장점도 있다고 생각합니다.
> 
> 위의 말씀에서 구현체 / 호출부 분리 구현이 어떤 의미가 있을까요? 분리 구현이 서로 다른 사람이 각각 ViewModel과 Domain을 따로 개발하고 protocol로 대화한다는 의미라면 이 방법에 찬성합니다.

@sustainable-git 

`Hexagonal Architecture` 라는걸 처음 접해서 특별히 염두하진 않았습니다.   
말씀 듣고 찾아봐서 이해가 완전하진 않은데, `DomainInterface` 가 이 구조에서 `Adapter` 역할로 볼 수 있는 걸까요?
의도는 말씀해주신 구조에서 원하는 대체가능한? `Adapter`의 역할이 된다는게 결국 의존성이 분리되었다로 볼 수도 있을것 같아요!   

단방향 의존 관계더라도 결국 Presentation Layer의 변화가 Domain Layer에 Repository로 전달 되어야하는 부분 떄문에, 

[iOS Clean Architecture-MVVM](https://github.com/kudoleh/iOS-Clean-Architecture-MVVM/blob/20edb84d7235dcad0bd1266614b1a46f71b607f2/ExampleMVVM/Presentation/MoviesScene/MoviesList/ViewModel/MoviesListViewModel.swift#L49) 이 경우에는 클린아키텍처 구조가 안쪽으로 의존하는 형태의 구조이기 때문에,   
Presentation Layer (모듈)이 Domain Layer (모듈)과 Entity Layer (모듈)을 모두 의존하는 형태입니다.
말씀하신 `import Domain`의 형태가 자연스럽다고 생각합니다.
> `의존 방향을 단방향으로` 해서 테스트에 용이하거나 유지보수에 좋은 구조라는 부분이 클린아키텍처에 핵심으로 이해했습니다.

---

제가 말씀 드리고자하는 차이점은 `모듈간의 의존 관계 분리`가 메인으로 볼 수 있을 것 같아요
> 기대한 구조와 살짝 다른 부분이 있는데 기대한 구조로 바라봐 주시면 좋을것 같습니다.. ㅠㅠ

| Before | Now | After |
|:--:|:--:|:--:|
| <img width="579" alt="image" src="https://user-images.githubusercontent.com/24707229/209611059-a250b6b7-b327-4015-90bc-a675b4c05a69.png"> | <img width="536" alt="image" src="https://user-images.githubusercontent.com/24707229/209612206-cb78625d-22a4-4f33-849a-c9a6b7f7cfd3.png"> | <img width="542" alt="image" src="https://user-images.githubusercontent.com/24707229/209611605-3105964a-d353-4baf-9c7a-8521c66b5a74.png"> | 
||  ![graph-before](https://user-images.githubusercontent.com/24707229/209611649-8cbb66d9-9fab-4eed-9365-0d0a150f046c.png) | ![graph-after](https://user-images.githubusercontent.com/24707229/209611657-ec07548f-59f4-4863-89a9-cec87c8efb03.png) |
||현재 코드|제가 기대한 구현 - 수정한 내용은 추가 커밋에 적용|

Interface 없이 Domain을 직접 UserInterface에서 import 해서 사용하는 경우 두 모듈은 직접 의존하게 됩니다.  
그렇다고 `A` 의존을 끊는 다는건 Domain 이라는 일종의 비즈니스 로직 모듈을 App (최상위) 에서 분리하는거라 안된다고 생각합니다.  
지금 제가 집중한 부분은 B 의존을 의존성 역전으로 분리하고 Domain 모듈의 구현체 주입을 App -> UserInterface (ModelContainer) 인데

2022-12-27 09:33 UTC, sustainable-git commented on Targets/Ticlemoa/Sources/TiclemoaApp.swift
> +    )
@keeplo 
model container를 ContentView로 옮기면 `import Domain`도 뺄 수 있지 않을까요?

2022-12-27 13:05 UTC, keeplo commented on Targets/Ticlemoa/Sources/TiclemoaApp.swift
> +    )
@sustainable-git 

`ArticleModel()` 요녀석과 `TagModel()` 요녀석은 `Domain`의 사용자 타입이기 때문에,  
`App` 에서 `Domain`을 `import` 해서 인스턴스화해서 주입해주어야합니다!

2022-12-27 13:34 UTC, sustainable-git commented on Targets/Ticlemoa/Sources/TiclemoaApp.swift
> +    )
@keeplo 
앗 이해했습니다. UserInterface가 Domain을 바라보지 않게 하기 위함이었군요!

2022-12-30 12:29 UTC, joseph704 approved these changes

2022-12-31 15:24 UTC, merged