[Feature] CustomButtomSheet에 handleBar Hidden 기능
depromeet/nyongnyong_iOS pull request #86
Opened 2022-12-30 09:40 UTC by sustainable-git

## 📌 배경

close #64

## 내용
- CustomBottomSheet가 handleBar를 보여줄지 말지 초기화할 수 있도록 함
  - handleBar가 없는 초기값을 가지도록 하였습니다.

## 테스트 방법 (optional)
- MyPage에서 회원탈퇴를 누른다

## 스크린샷 (optional)
|수정 전|수정 후|
|:-:|:-:|
|<img width=300 src="https://user-images.githubusercontent.com/81242125/210056013-c77d6a5e-c45c-4eef-8835-b24d5ec14ae5.png">|<img width=300 src="https://user-images.githubusercontent.com/81242125/210056022-ccf1060f-0c55-4b97-9496-b2baba363aa0.png">|

2022-12-30 12:31 UTC, joseph704 approved these changes
감사합니다!

2022-12-30 17:50 UTC, joseph704 requested changes

2022-12-30 17:50 UTC, joseph704 commented on Targets/UserInterface/Sources/Utils/Extensions/View+BottomSheet.swift
>          let keyWindow = UIApplication.shared.connectedScenes.compactMap { ($0 as? UIWindowScene)?.keyWindow }.first!
```suggestion
        let keyWindow = UIApplication.shared.connectedScenes.compactMap { ($0 as? UIWindowScene)?.keyWindow }.first
```

ticlmoaBottomSheet 메소드 호출하는 View에서 강제 추출로 인해 preViews 실패가 되는데 강제 추출 제거해 주실 수 있으신가요?

2022-12-31 12:55 UTC, keeplo approved these changes
고생하셨습니다

2023-01-01 03:42 UTC, kipsong133 approved these changes
고생하셨습니다~!

2023-01-02 04:15 UTC, sustainable-git commented on Targets/UserInterface/Sources/Utils/Extensions/View+BottomSheet.swift
>          let keyWindow = UIApplication.shared.connectedScenes.compactMap { ($0 as? UIWindowScene)?.keyWindow }.first!
#102 에서 수정하겠습니다. 감사합니다.

2023-01-02 06:34 UTC, joseph704 approved these changes
고생하셨습니다!

2023-01-06 15:30 UTC, merged